# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false # setting this false b/c of rcpp attribute error

cache:
  packages: true

before_install:
  - tlmgr install index
  - export PACKAGE_NAME=patchMatchR
  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
  - source travis_helpers.sh
  - rm travis_helpers.sh
  - start_xvfb ;
  - v8_install ;
  - Rscript -e 'install.packages("rsvd")'
  - Rscript -e 'install.packages("magic")'
  - Rscript -e 'install.packages(c("psych","colormap"))'
  - Rscript -e 'install.packages("RcppEigen")'
  - gh_binary_install  stnava/ITKR ANTsX/ANTsRCore ANTsX/ANTsR
